# Generated by Django 3.2.6 on 2021-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Publisher', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
