# Generated by Django 3.2.6 on 2021-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='enroll_code',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='mobile_number',
            field=models.BigIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
